prd:
  catalog_name: mlops_dev
  schema_name: kirancr2
  pipeline_id: 89bb47d9-ec09-4972-a57a-fc29a8eb90d2

acc:
  catalog_name: mlops_dev
  schema_name: kirancr2
  pipeline_id: 89bb47d9-ec09-4972-a57a-fc29a8eb90d2

dev:
  catalog_name: mlops_dev
  schema_name: kirancr2
  pipeline_id: 89bb47d9-ec09-4972-a57a-fc29a8eb90d2



experiment_name_basic: /Shared/yellow-taxi-basic
experiment_name_custom: /Shared/yellow-taxi-custom
experiment_name_fe: /Shared/yellow-taxi-fe

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - fare_amount
  - passenger_count
  - trip_distance
  - payment_type_discount


cat_features:
  - PULocationID
  - transaction_month
  - transaction_day
  - transaction_hour
  - transaction_year
  - payment_type


target: total_amount
