catalog_name: mlops_dev
schema_name: kirancr2
experiment_name_basic: /Shared/yellow-taxi-basic
experiment_name_custom: /Shared/yellow-taxi-custom
experiment_name_fe: /Shared/yellow-taxi-fe

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - fare_amount
  - passenger_count
  - trip_distance
  - payment_type_discount


cat_features:
  - PULocationID
  - transaction_month
  - transaction_day
  - transaction_hour
  - transaction_year
  - payment_type


target: total_amount
